### ISSUE TITLE
Can we put the ELO score in the best networks table?

### ISSUE THREAD

**Issue by marcocalignano** [gcp/leela-zero-server#79] opened 2018-05-04 11:09 UTC
I would like to have a new column for the ELO score in the table on the left.

**Comment by Mardak** [comment] 2018-05-05 15:51
I believe why this is not so trivial is that ELO is currently something that only gets computed for the graph's json data endpoint. Potentially that logic could be refactored and shared with the root page too, although that would probably increase the number of mongodb queries significantly… ?

**Comment by roy7** [comment] 2018-05-05 21:02
If I write this myself, the solution I'd take is just to cache the values when they are calculated and then read the cache elsewhere (such as during networks table being made). When the matches cache is flushed, flush the ELO cache too and store it fresh.

**Comment by gcp** [comment] 2018-05-07 09:38
If I schedule 2 matches for the same network, what will happen with the ELO?

**Comment by marcocalignano** [comment] 2018-05-07 10:02
The ELO for a best network is calculated when the network wins against the previous best network. Afterwords it does not change otherwise the whole chart would go up and down every time you add matches. I would like to have the ELO of the network that PASS the gating, so where in the chart you have a blue dot with an ELO value and a name. I'd like to have the same in the left table (name , ELO value)

**Comment by roy7** [comment] 2018-05-07 12:33
@gcp I need to review teh code to be certain. I think I sort the match results by timestamp, and compare them in a chain starting from the first match. A vs B, calculate A's ELO where B started at 0. Then step to C vs A or B. Then step to D vs A B or C. Etc. All the way to most recent match.

A 2nd match between ELF and a network won't blend or average. It'll either be the new ELO or the old ELO. It might generate the plot point twice (training_games, ELO) with the same X axis location. There was discussion on Discord if test matches should use the training_games of the opponent for the X axis instead of the test's network's training_games. This would avoid how test matches for winner "skew left" and look much higher ELO on the graph than the networks they beat. But maybe it's more accurate as-is. I don't know... any thoughts on that?

In terms of repeating matches vs multiple opponents we can add support as needed to work however we expect. Multiple points with same hash should be doable, I don't think vega-lite is using the hash codes for anything specific. It should just be a data label and the points themselves are one plot point per match.

**Comment by gcp** [comment] 2018-05-07 12:42
> There was discussion on Discord if test matches should use the training_games of the opponent for the X axis instead of the test's network's training_games.

I don't see why. They are mostly left now on the graph because they're from the 256x20 nets which lag in amount of training? But those are positioned correctly, and accurately reflect that they lack that data.

**Comment by roy7** [comment] 2018-05-07 13:01
Yes, it's just it makes those tests look much stronger than they really were. Like the test around 6.2M games wasn't really 800 ELO stronger than the network it played against.

We could just special case ELF hash to use opponent X instead of the one you selected. Then if we plot multiple ELF matches they'll flow along. Could even make a special ELF data mark instead of normal TEST mark. If the idea is to plot LZ strength over time on how well it can win vs ELF.

**Comment by Mardak** [comment] 2018-05-08 06:05
What's the expected behavior of a network having multiple matches? Should the ELO be averaged across the matches? Should the graph show the average with a single point or each individual match result has its own point?

To be clear, multiple points for a network can be shown on the graph without issue. However, if it's a "best" network, the line needs to have a single point to go to, and this point could be different from the others. Similarly, this single point would be used to calculate the ELO for any other matches that use it as the anchor / reference.

For example, the 3 TEST dots near the top middle could be the same network testing against 3 other networks. And the 2nd-rightmost PASS dot with a line through it could be a promoted network with the average ELO of the two nearby TEST dots of the same network.
![screen shot 2018-05-07 at 11 01 47 pm](https://user-images.githubusercontent.com/438537/39740553-015208b8-524b-11e8-9b18-3a908738e2f8.png)

**Comment by roy7** [comment] 2018-05-08 14:36
I'm assuming (@gcp confirm?) that multiple testing of same network would only be for test networks, not promoted real networks. So line drawing should not be a problem. I'd hazard a further guess this is mostly about ELF and wanting to test ELF vs additional networks over time so we can see if we're getting stronger vs ELF.

**Comment by gcp** [comment] 2018-05-08 14:58
It's meant for testing yes. Currently I avoid playing a second match with a new network.

**Comment by roy7** [comment] 2018-05-08 15:06
If you want to throw caution to the wind we could queue ELF against 05b723d0 as a test and fix anything that breaks. ;) (Be sure it's a test.)

**Comment by Mardak** [comment] 2018-05-08 15:46
Just to confirm, the current behavior does seem to just use the latest match's result for the network1's ELO calculation. Current ELF is 11,198 for reference.

**Comment by Mardak** [comment] 2018-05-09 19:01
Elo in table fixed by #107

**Closed** 2018-05-09 22:50 UTC
Labels: enhancement
