### ISSUE TITLE
Please, please. Could you fix the graph?

### ISSUE THREAD

**Issue by Marcin1960** [gcp/leela-zero-server#108] opened 2018-05-08 08:46 UTC
Could someone test the new graph on a few different browsers and configurations,
and make it work again, please?

**Comment by Mardak** [comment] 2018-05-08 09:13
What browsers does it not work on? Sounds like from your previous report, Pale Moon.

**Comment by Marcin1960** [comment] 2018-05-08 09:35
It stopped to work on Pale Moon in my case, but others are complaining too.

**Comment by Mardak** [comment] 2018-05-08 09:41
Others.. also using Pale Moon?

**Comment by Marcin1960** [comment] 2018-05-08 09:46
I did not ask them. And now I cannot find their comments.

**Comment by roy7** [comment] 2018-05-08 15:13
Someone checked it out with Pale Moon on discord and the issue is that Pale Moon is based on a very old Firefox as I understand it, before the current javascript spec was finalized and it doesn't fully support the standard javascript the chart is using?

**Comment by Mardak** [comment] 2018-05-08 20:05
@Marcin1960 You said you've tested on 3 different configurations, and they're all broken. What are those configurations?

**Comment by Mardak** [comment] 2018-05-08 20:08
You also suggested that the graph is probably broken for most people https://github.com/gcp/leela-zero/issues/1362#issuecomment-387061196 what's the basis for that?

**Comment by Marcin1960** [comment] 2018-05-09 07:43
"You also suggested that the graph is probably broken for most people gcp/leela-zero#1362 (comment) what's the basis for that?"

I said something else: "Anyway graph does not work anymore for several systems (all different 3 of mine), so it does not matter for many if not for the most.".

But it might that the problem is caused by what is written above "the issue is that Pale Moon is based on a very old Firefox as I understand it, before the current javascript spec was finalized"

I rarely update or change my software. This could be the reason - new graph is not backward compatible.

**Comment by Mardak** [comment] 2018-05-09 17:37
"so [the graph being broken] does not matter for many if not for the most." Am I misunderstanding your statement?

In any case, I did download Pale Moon, and it does look very old. No support for `async` nor `fetch` from a quick glance.

**Comment by roy7** [comment] 2018-05-09 17:49
@Mardak He may have meant the problem wasn't happening for many or most people. IE, this problem doesn't matter for most people because most people are using newer browsers that are working fine.

**Comment by Mardak** [comment] 2018-05-09 19:01
Fixed by #114

**Comment by Marcin1960** [comment] 2018-05-09 19:07
Hooray! Graph works now.

**Closed** 2018-05-09 22:50 UTC
