### ISSUE TITLE
Mouseover tooltip for match time start is in ms now

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero-server#40] opened 2018-03-29 22:23 UTC
Such as https://imgur.com/a/ML7Q5

**Comment by rchs819** [comment] 2018-03-30 00:32
Is there any daylight saving change on the server?

It looks like the timestamp generated is 1 hour ahead, ended up in negative ms.

**Comment by roy7** [comment] 2018-03-30 00:50
@gcp I'm not sure how to tell. It's hosted in Europe someplace.

$ date
Fri Mar 30 02:49:24 CEST 2018
$ date -u
Fri Mar 30 00:49:26 UTC 2018

The tooltips on web page look correct to me. I'm in Florida, USA where we do have daylight savings changes.

**Comment by rchs819** [comment] 2018-03-30 02:06
@roy7 could you try
```
date +%z
```
This would give current timezone offset, which should consistent with the code (+0100)

https://github.com/gcp/leela-zero-server/blob/613151cdb5ca66b6783c8bb85cefc674751f3b16/static/timeago.js#L43

**Comment by roy7** [comment] 2018-03-30 02:18
$ date +%z
+0200

**Comment by rchs819** [comment] 2018-03-30 02:29
cool, we found the cause.

I'll try to fix this, so that the timestamp generated should factor in the timezone change.

**Comment by roy7** [comment] 2018-03-30 02:35
@Mardak origianlly wrote the code if he wants to chime in. A solution that won't break when daylight saving flips back would be great. :)

**Comment by Mardak** [comment] 2018-03-30 03:16
The website seems to have a hardcoded message of "Times are in GMT+0100 (CET)"
https://github.com/gcp/leela-zero-server/blob/dfc0657534c1a49faf8cc2ebb55480bd617dfba8/server.js#L1156

But https://github.com/gcp/leela-zero-server/issues/40#issuecomment-377426683 seems to indicate it's on UTC+2 (CEST) now.

If `server.js` is updated to provide the correct "Times are in GMT+…" message, `timeago.js` could parse that to use the appropriate offset.

**Comment by Mardak** [comment] 2018-03-30 03:18
Alternatively, if the times were all fixed to just UTC+0 (or I suppose even UTC+1), the timeago.js tooltip wouldn't need to parse for the offset.

**Comment by roy7** [comment] 2018-03-30 03:56
https://github.com/gcp/leela-zero-server/pull/43 seems like a clean easy fix. Any objections/alternatives before I merge that tomorrow? I think we were originally using CET+1 since that was native server time back then.

**Comment by Mardak** [comment] 2018-03-30 06:06
Looks like this is live? Here's the current page compared to what was originally filed (same matches different times):
<img width="541" alt="image" src="https://user-images.githubusercontent.com/438537/38126447-955422ea-33a5-11e8-8b78-da6269877064.png">

orig:
![image](https://user-images.githubusercontent.com/438537/38126457-a61afcfc-33a5-11e8-9734-fc71eb5f0cf7.png)

Should `next` be merged to `master` if it's live?

**Comment by roy7** [comment] 2018-03-30 13:07
Yeah I went ahead and made it live but open for more feedback if anyone has any. :)

Web site runs off /next but I'll roll it all over to master shortly.

**Closed** 2018-03-30 13:07 UTC
Labels: bug
